plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

theme: jekyll-theme-cayman

title: 欽ちゃんの仮装大賞 パネル再現ツール
description: 欽ちゃんの仮装大賞で使われていたパネルをwebアプリのツールとして再現してみました。操作方法は A S D キーでカウントアップ、R キーでリセットできます。ヘルプボタンからスマホ向けのボタンを表示する機能がありますので、スマホユーザーの方はそちらのボタンを利用して楽しんでください。
google_analytics: UA-122581403-2
